### ISSUE TITLE
PUT endpoint should not create a new Schema

### ISSUE THREAD

**Issue by theisuru** [EBIBioSamples/json-schema-store#10]
Only POST endpoint should be able to create new Schema. If new ID is present in a PUT request, we should show it as an validation error.

**Comment by Hashan-Rashmi-Perera** [comment]
> Only POST endpoint should be able to create new Schema. If new ID is present in a PUT request, we should show it as an validation error.
does post endpoint allow to insert only?

**Comment by Hashan-Rashmi-Perera** [comment]
> Only POST endpoint should be able to create new Schema. If new ID is present in a PUT request, we should show it as an validation error.

does post endpoint allow to insert only?

**Comment by theisuru** [comment]
Yes, not updates on POST. If id already exists, its should be an error

**Comment by Hashan-Rashmi-Perera** [comment]
> Yes, not updates on POST. If id already exists, its should be an error

Both 2 issues were resolved
