### ISSUE TITLE
Response format 

### ISSUE THREAD

**Issue by theisuru** [EBIBioSamples/json-schema-store#8]
We would expect response to have a similar format to the request. It would be easier if we can start from response, edit it and send back for the update endpoint. 
Affected endpoints:
- POST
- PUT 
- GET by id

**Comment by Hashan-Rashmi-Perera** [comment]
> We would expect response to have a similar format to the request. It would be easier if we can start from response, edit it and send back for the update endpoint.
> Affected endpoints:
> 
> * POST
> * PUT
> * GET by id

Issue is resolved
